
on script unload:
  loop {-evilSkript::bossMobs::*}:
    killBoss(loop-index)
  delete {-evilSkript::bossMobs::*}
  broadcast "&4{&8Evil Skript&4} &4Unloading evil script..."

on script load:
  scriptBroadcast("&9Loading evil script...")

  set {-netherbreach} to false
  set {-apocalypse} to false
  set {-bigraid} to false
  scriptBroadcast("&4Clearing World Events...")

function killBoss(uuid: text):
	delete getByUUID({_uuid})

on place of any bed:
	add event-block to {evilSkript::bed::*}
	rpgLog("%player% placed bed in %world% at %location of block%")

on break of any bed:
	remove event-block from {evilSkript::bed::*}
	rpgLog("%player% broke bed in %world% at %location of block%")

command /wherePlayerBeds:
  executable by: anyone
  trigger:
    command executor has permission "rpg.control"
    loop {evilSkript::bed::*}:
      send "Player Bed Detected At: %location of loop-value%" to command executor
  
on spawn:
  spawn reason is natural
  spawn reason is not mob spawner
  entity is a monster
  set {_chance} to log({rpgdiff}) * 12.5
  {_chance} <= 0:
    stop
  if entity is a zombie:
    if {-netherbreach} is true:
      spawn 1 zombified piglin at entity
      spawn 1 piglin at entity
      chance of 10%:
        spawn 1 piglin brute at entity
    if entity is not a baby zombie:
      chance of ({_chance}/2.5)%:
        makeSpecial(entity)
      chance of ({_chance}/2.5)%:
        makeSummoner(entity)
    else:
      chance of ({_chance}/2.5)%:
        makeSpecial(entity)     
    
  else if entity is a skeleton:
    if {-netherbreach} is true:
      spawn 1 wither skeleton at entity
    chance of ({_chance}/2.5)%:
      makeSpecial(entity)
    chance of ({_chance}/2.5)%:
      makeSummoner(entity)
  else if entity is a spider:
    if {-netherbreach} is true:
      spawn 1 hoglin at the entity
    chance of ({_chance}/2.5)%:
      makeSpecial(entity)
  else if entity is a enderman:
    chance of ({_chance}/2.5)%:
      makeSpecial(entity)
  else if entity is a creeper:
    if {-netherbreach} is true:
      spawn 1 blaze at entity
    chance of ({_chance}/2.5)%:
      makeSpecial(entity)
  else if entity is a slime:
    if {-netherbreach} is true:
      spawn 1 magma cube at entity
  else if entity is a phantom:
    if {-netherbreach} is true:
      spawn 1 ghast at entity

  if {-apocalypse} is true:
    isMonster(entity) is true:
      set {_n} to a random integer between 1 and 10
      if (1.1^({rpgdiff} - 1)) is greater than 2:
        set {_n} to {_n} * 2
      else:
        set {_n} to floor({_n} * (1.1^({rpgdiff} - 1)))
      loop {_n} times:
        spawn 1 zombie at entity:
          chance of ({_chance} / 1.25)%:
            makeSpecial(entity)


on spawn:
  isMinion(entity) is false
  if at least one of:
    entity is a monster
    entity is an iron golem
    entity is a wolf
    entity is a polar bear
  then:
    if {rpgdiff} is not set:
      set {rpgdiff} to 1
    set attack damage attribute of entity to (1.1^({rpgdiff} - 1)) * attack damage attribute of entity
    set maximum health of entity to (1.1^({rpgdiff} - 1)) * maximum health of entity
    heal entity
  isMonster(entity) is true:
    time in world of entity is between 19:00 and 5:00
    {-evilSkript::%entity%::isBoss} is false
    set {_itemchance} to 2.5
    if at least one of:
      {-netherbreach} is true
      {-apocalypse} is true
      {-bigraid} is true
    then:
      set {_itemchance} to 5
    chance of {_itemchance}%:
      set helmet of entity to generateLootHelmet()
    chance of {_itemchance}%:
      set chestplate of entity to generateLootChestplate()
    chance of {_itemchance}%:
      set leggings of entity to generateLootLeggings()
    chance of {_itemchance}%:
      set boots of entity to generateLootBoots()
    chance of {_itemchance}%:
      set held item of entity to generateLootSword()
    chance of {_itemchance}%:
      set off hand item of entity to generateLootShield() 

on death:
  victim is a monster:
    remove victim from {-evilSkript::bossMobs::*}
    
    set {rpgdiff} to {rpgdiff} + 0.00025
    if mod({rpgdiff}, 0.2) is 0:
      broadcast "Difficulty is now: %{rpgdiff}%"

      
    set {_ran} to 0
    set {_drop} to rotten flesh
    if victim is a zombie:
      chance of {rpgdiff}%:
        set {_drop} to rotten flesh
        set {_drop} to addImbue({_drop}, "Cursed")
        set name of {_drop} to "&4Cursed Flesh"
        set {_ran} to a random integer between 1 and 3
    if victim is a skeleton:
      chance of {rpgdiff}%:
        set {_drop} to bone
        set {_drop} to addImbue({_drop}, "Cursed")
        set name of {_drop} to "&4Cursed Bone"
        set {_ran} to a random integer between 1 and 3
    loop {_ran} times:
      add {_drop} to the drops

  victim is a player:
    set {rpgdiff} to {rpgdiff} - 5
    if {rpgdiff} is less than 0.05:
      set {rpgdiff} to 0.05
    broadcast "Difficulty is now: %{rpgdiff}%"

every 5 seconds:
  if {rpgdiff} is less than 0.01:
    set {rpgdiff} to 0.01
  if {rpgdiff} is greater than 50:
    set {rpgdiff} to 50
  {-allowEvents} is true
  if time in world "world" is between 19:00 and 5:00:
    if:
      {-netherbreach} is false
      {-apocalypse} is false
      {-bigraid} is false
    then:
      if {lastInvasion} is not set:
        set {lastInvasion} to 1.5 hours ago
      difference between {lastInvision} and now is more than 1 hour:
        set {_chance} to log({rpgdiff}) * 12.5 / 75
        if {_chance} > 0:
          chance of {_chance}%:
            set {lastInvasion} to now
            set {_odds} to random number between 1 and 100
            if {_odds} is less than 30:
              set {-netherbreach} to true
              broadcast "&4A Nether Breach Opens..."
            else if {_odds} is less than 100:
              set {-apocalypse} to true
              broadcast "&4The Undead Grow Restless..."              
  else:
    if {-netherbreach} is true:
      set {-netherbreach} to false
      broadcast "&4A Nether Breach Closes..."
    if {-apocalypse} is true:
      set {-apocalypse} to false
      broadcast "&4The Undead are put to rest..."

  if time in world "world" is between 7:00 and 17:00:
    if:
      {-netherbreach} is not true
      {-apocalypse} is not true
      {-bigraid} is not true
    then:
      if {lastInvasion} is not set:
        set {lastInvasion} to 0.5 hours ago
      difference between {lastInvision} and now is more than 1 hour:
        set {_chance} to log({rpgdiff}) * 12.5 / 75
        if {_chance} > 0:
          chance of {_chance}%:
            set {lastInvasion} to now
            set {_odds} to random number between 1 and 100
            if {_odds} is less than 100:
              set {-bigraid} to true
              broadcast "&4Pillager raiding parties cometh..."
  else:
    if {-bigraid} is true:
      set {-bigraid} to false
      broadcast "&4The raiding parties retreat..."
  

  
on weather change to rain:
  chance of 15%:
    set {-severestorms} to true
    loop all players:
      if at least one of:
        biome of loop-player is desert
        biome of loop-player is badlands
      then:
        send "&6A severe sandstorm picks up!" to loop-player
      else:
        send "&4An Acid Rain Pours!" to loop-player

on weather change:
  weather is not rain:
    if {-severestorms} is not false:
      {-severestorms} is true:
        broadcast "&cSevere Storms End..."
      set {-severestorms} to false

command /allowWorldEvents <boolean>:
  trigger:
    if command executor does not have permission "rpg.spawn":
      send "&cYou do not have access to that command." to command executor
      stop
    set {-allowEvents} to arg 1
    broadcast "{-allowEvents} set to %{-allowEvents}%" 

command /worldevents <text> <boolean>:
  trigger:
    if command executor does not have permission "rpg.spawn":
      send "&cYou do not have access to that command." to command executor
      stop
    if arg 1 is "severe storms":
      set {-severestorms} to arg 2 
      if arg 2 is true:
        set weather in "world" to rain
      scriptDebugBroadcastType("worldevents", "Setting {-severestorms} to %arg 2%")
      broadcast "&c{-severestorms} set to %arg 2%"
    else if arg 1 is "nether breach":
      set {-netherbreach} to arg 2
      if arg 2 is true:
        set time in "world" to 20:00
      scriptDebugBroadcastType("worldevents", "Setting {-neatherbreach} to %arg 2%")
      broadcast "&c{-netherbreach} set to %arg 2%"
    else if arg 1 is "apocalypse":
      set {-apocalypse} to arg 2
      if arg 2 is true:
        set time in "world" to 20:00
      scriptDebugBroadcastType("worldevents", "Setting {-neatherbreach} to %arg 2%")
      broadcast "&c{-apocalypse} set to %arg 2%"
    else if arg 1 is "big raid":
      set {-bigraid} to arg 2
      if arg 2 is true:
        set time in "world" to 8:00
      scriptDebugBroadcastType("worldevents", "Setting {-bigraid} to %arg 2%")
      broadcast "&c{-bigraid} set to %arg 2%"
          
    else:
      send "&cInvalid World Event." to command executor 

command /displayevents:
  trigger:
    broadcast "&cBroadcasting Events"
    broadcast "&6Severe Storms is %{-severestorms}%"
    broadcast "&6Nether Breach is %{-netherbreach}%"
    broadcast "&6Apocalypse is %{-Apocalypse}%"

command /clearSpawn:
  executable by: anyone
  trigger:
    if command executor does not have permission "rpg.spawn":
      send "&cYou do not have access to that command." to command executor
      stop    
    else:
      loop all entities in radius 100 around spawn:
        loop-entity is not a player
        isFriendlyMob(loop-entity) is false
        delete loop-entity
    
      
function makeSpecial(entity: entity):
  {_entity} is a zombie:
    if {_entity} is not a baby zombie:
      set attack damage attribute of {_entity} to 1.8 * attack damage attribute of {_entity}
      set movement speed attribute of {_entity} to 1.2 * movement speed attribute of {_entity}
      set maximum health of {_entity} to 2.2 * maximum health of {_entity}
      heal {_entity}
      equip {_entity} with iron helmet
      equip {_entity} with iron chestplate
      equip {_entity} with iron leggings
      equip {_entity} with iron boots
      set {_entity}'s held item to iron sword
      loop 2 times:
        spawn a skeleton at {_entity}
    else:
      set attack damage attribute of {_entity} to 2.0 * attack damage attribute of {_entity}
      set movement speed attribute of {_entity} to 1.5 * movement speed attribute of {_entity}
      set maximum health of {_entity} to 2.0 * maximum health of {_entity}
      set size of {_entity} to 1.25 * size of {_entity}
      heal {_entity}
      equip {_entity} with leather helmet
      equip {_entity} with leather chestplate
      equip {_entity} with leather leggings
      equip {_entity} with leather boots
      set {_entity}'s held item to gold sword
      loop 2 times:
        spawn a skeleton at {_entity}
  else if {_entity} is a skeleton:
    set attack damage attribute of {_entity} to 2.0 * attack damage attribute of {_entity}
    set movement speed attribute of {_entity} to 1.3 * movement speed attribute of {_entity}
    set maximum health of {_entity} to 1.7 * maximum health of {_entity}
    equip {_entity} with chain helmet
    equip {_entity} with chain chestplate
    equip {_entity} with chain leggings
    equip {_entity} with chain boots
    set {_entity}'s held item to iron sword
    loop 2 times:
      spawn a zombie at {_entity}
  else if {_entity} is a spider:
    loop 3 times:
      spawn a cave spider at {_entity}
  else if {_entity} is an enderman:
    set attack damage attribute of {_entity} to 1.5 * attack damage attribute of {_entity}
    set movement speed attribute of {_entity} to 2.0 * movement speed attribute of {_entity}
    set maximum health of {_entity} to 1.5 * maximum health of {_entity}
    heal {_entity}
    loop 3 times:
      spawn a shulker at {_entity}
  else if {_entity} is a creeper:
    set movement speed attribute of {_entity} to 2 * movement speed attribute of {_entity}
    set maximum health of {_entity} to 5.0 * maximum health of {_entity}
    set {-evilSkript::%{_entity}%::disease} to true
    heal {_entity}
    loop 3 times:
      spawn a creeper at {_entity}
  set {_itemchance} to 20
  chance of {_itemchance}%:
    set helmet of {_entity} to generateLootHelmet()
  chance of {_itemchance}%:
    set chestplate of {_entity} to generateLootChestplate()
  chance of {_itemchance}%:
    set leggings of {_entity} to generateLootLeggings()
  chance of {_itemchance}%:
    set boots of {_entity} to generateLootBoots()
  chance of {_itemchance}%:
    set held item of {_entity} to generateLootSword()
  chance of {_itemchance}%:
    set off hand item of {_entity} to generateLootShield() 

function summonButcher(player:player, chance:number):
  scriptDebugBroadcastType("difficulty", "Attempting to spawn a Butcher at %{_player}%") 
  world of {_player} is "world"
  loop {evilSkript::bed::*}:
    set {_v} to the vector between {_player} and location of loop-value
    if the length of {_v} is less than 26: 
      stop
  set {_loc} to location of {_player}
  chance of {_chance}%:
    broadcast "A presence of evil surrounds %{_player}%!" 
    wait 15 seconds
    spawn 1 zombie at the location above {_loc}:
      set the zombie's display name to "&4The Butcher"
      set attack damage attribute of the zombie to 2.5 * attack damage attribute of the zombie
      set movement speed attribute of the zombie to 2.0 * movement speed attribute of the zombie
      set maximum health of the zombie to 200
      heal the zombie
      set {_temp} to the zombie
      set {-evilSkript::%{_temp}%::isBoss} to true
      set {-evilSkript::%{_temp}%::isButcher} to true
      set helmet of the zombie to generateLootHelmet()
      set chestplate of the zombie to generateLootChestplate()
      set leggings of the zombie to generateLootLeggings()
      set boots of the zombie to generateLootBoots()
      set {_odds} to a random integer between 0 and 1
      if {_odds} is 0:
        set held item of the zombie to generateLootSword()
        set held item of the zombie to generateLegendaryLore(held item of the zombie, "Butcher")
      else:
        set held item of the zombie to generateLootAxe()
        set held item of the zombie to generateLegendaryLore(held item of the zombie, "Butcher")
      set off hand item of the zombie to generateLootShield() 
      chance of (2 * {rpgdiff})%:
        set helmet of the zombie to generateMythicLore(helmet of zombie)
      chance of (2 * {rpgdiff})%:
        set chestplate of the zombie to generateMythicLore(chestplate of zombie)
      chance of (2 * {rpgdiff})%:
        set leggings of the zombie to generateMythicLore(leggings of zombie)
      chance of (2 * {rpgdiff})%:
        set boots of the zombie to generateMythicLore(boots of zombie)
      chance of (2 * {rpgdiff})%:
        set off hand item of the zombie to generateMythicLore(off hand item of zombie)
      chance of (2 * {rpgdiff})%:
        set held item of the zombie to generateMythicLore(held item of zombie)	
      scriptDebugBroadcastType("difficulty", "Spawning a Butcher at %{_player}%")  
      add uuid of the zombie to {-evilSkript::bossMobs::*}

command /spawnButcher <player> <number>:
  executable by: anyone
  trigger:
    if command executor is a player:
      if command executor does not have permission "rpg.spawn":
        send "&4You do not have access to that command." to command executor
    scriptDebugBroadcastType("difficulty", "%command executor% spawns a Butcher at %arg 1%") 
    summonButcher(arg 1, arg 2)

command /spawnrates:
  executable by: anyone
  trigger:
    broadcast "Special/Summoner Chance: log(%{rpgdiff}%) * 12.5 / 2.5 = %log({rpgdiff}) * 12.5 / 2.5% PERCENT"
    broadcast "Boss Chance: log(%{rpgdiff}%) * 12.5 / 50 = %log({rpgdiff}) * 12.5 / 50% PERCENT"
    broadcast "Butcher Chance: log(%{rpgdiff}%) * 12.5 / 100 = %log({rpgdiff}) * 12.5 / 100% PERCENT"
    broadcast "Netherbreach/Apocalypse Chance: log(%{rpgdiff}%) * 12.5 / 75 = %log({rpgdiff}) * 12.5 / 100% PERCENT"
    broadcast "Mobs Attack Damage Bonus: %(1.1^({rpgdiff} - 1))%x"
    broadcast "Mobs Health Bonus: %(1.1^({rpgdiff} - 1))%x"
        
on explosion:
  if event-entity is a creeper:
    creeperDetonate(event-entity)


on death:
  victim is a creeper:
    creeperDetonate(victim)

function creeperDetonate(entity:entity):
  if {-evilSkript::%{_entity}%::disease} is true:
    createWorldEffect(location of {_entity}, "disease", 20 seconds, {_entity})
  if {-evilSkript::%{_entity}%::detonator} is true:
    create an explosion with force 3 at {_entity}
    loop blocks in radius 5.99 around {_entity}:
      loop-block is not air
      loop-block is not bedrock
      break loop-block naturally
    if {-evilSkript::%{_entity}%::crassus} is true:
      loop blocks in radius 7.99 around {_entity}:
        loop-block is not air
        if at least one of:
          loop-block is stone
          loop-block is deepslate
          loop-block is grass block
          loop-block is dirt
          loop-block is sand
          loop-block is red sand
        then:
          loop blocks in radius 1 around loop-block:
            loop-block-2 is not air
            loop-block-2 is not any ore
            loop-block-1 is not bedrock
            chance of 30%:
              set {_odds} to rollDice(1,100)
              if {_odds} is less than 10:
                set loop-block-1 to coal ore
              else if {_odds} is less than 20:
                set loop-block-1 to copper ore
              else if {_odds} is less than 50:
                set loop-block-1 to iron ore
              else if {_odds} is less than 80:
                set loop-block-1 to gold ore
              else if {_odds} is less than 85:
                if {-netherbreach} is true:
                  set loop-block-1 to glowstone block
                  exit 1 loop
                set loop-block-1 to redstone ore
              else if {_odds} is less than 95:
                set loop-block-1 to lapis lazuli ore
                if {-netherbreach} is true:
                  set loop-block-1 to quartz ore
                  exit 1 loop
              else if {_odds} is less than 98:
                set loop-block-1 to diamond ore
              else:
                if {-netherbreach} is true:
                  chance of 30%:
                    set loop-block-1 to ancient debris
                    exit 1 loop
                set loop-block-1 to emerald ore
                
    loop all entities in radius 24 around {_entity}:
      loop-entity is not a dropped item
      loop-entity is alive
      set {_v} to vector between {_entity} and loop-entity
      set y component of {_vec} to 0
      set {_vec} to normalized {_vec}
      push loop-entity {_vec} with force 3
      push loop-entity upwards with force 1.2
      damage loop-entity by 50 - (length of {_v} * 2)
    broadcast "&eDetonator Explosion!"
    
    
function makeSummoner(entity:entity):
  if at least one of:
    {_entity} is a skeleton
    {_entity} is a zombie
  then:
    set {_entity}'s held item to a stick
    set {-evilSkript::%{_entity}%::summoner} to true
    set {-evilSkript::%{_entity}%::summoncount} to 3

function makeBoss(entity:entity, boss: string):
  if {_boss} is "dune":
    set {_entity}'s display name to "&6Dune Revenant"
    set attack damage attribute of {_entity} to 2 * attack damage attribute of {_entity}
    set movement speed attribute of {_entity} to 2.0 * movement speed attribute of {_entity}
    set maximum health of {_entity} to 100
    heal {_entity}
    set {-evilSkript::%{_entity}%::dunerev} to true
    set {-evilSkript::%{_entity}%::isBoss} to true
    set helmet of {_entity} to generateLootHelmet()
    set chestplate of {_entity} to generateLootChestplate()
    set leggings of {_entity} to generateLootLeggings()
    set boots of {_entity} to generateLootBoots()
    set off hand item of {_entity} to generateLootShield()
    set held item of {_entity} to generateLootSword()
  if {_boss} is "detonator":
    set {_entity}'s display name to "&8Detonator"
    set movement speed attribute of {_entity} to 0.5 * movement speed attribute of {_entity}
    set maximum health of {_entity} to 200
    set {-evilSkript::%{_entity}%::detonator} to true
    set {-evilSkript::%{_entity}%::summoner} to true
    set {-evilSkript::%{_entity}%::summoncount} to 4
    set helmet of {_entity} to generateLootHelmet()
    set chestplate of {_entity} to generateLootChestplate()
    set leggings of {_entity} to generateLootLeggings()
    set boots of {_entity} to generateLootBoots()
    set off hand item of {_entity} to generateLootShield()
    set held item of {_entity} to generateLootSword()
    set leggings of {_entity} to generateLegendaryLore(leggings of {_entity}, "Detonator")
    chance of 30%:
      set {-evilSkript::%{_entity}%::crassus} to true 
      set {_entity}'s display name to "&eCrassus Detonator"  
    set {-evilSkript::%{_entity}%::isBoss} to true
    heal {_entity}
  if {_boss} is "captain":
    set {_entity}'s display name to "&4Pillage Captain"
    set movement speed attribute of {_entity} to 2.0 * movement speed attribute of {_entity}
    set attack damage attribute of {_entity} to 1.5 * attack damage attribute of {_entity}
    set maximum health of {_entity} to 100
    set {-evilSkript::%{_entity}%::isBoss} to true
    set {-evilSkript::%{_entity}%::summoner} to true
    set {-evilSkript::%{_entity}%::summoncount} to 5
    set helmet of {_entity} to generateLootHelmet()
    set chestplate of {_entity} to generateLootChestplate()
    set leggings of {_entity} to generateLootLeggings()
    set boots of {_entity} to generateLootBoots()
    set held item of {_entity} to generateLootSword()
    set helmet of {_entity} to generateLegendaryLore(helmet of {_entity}, "Pillage_Captain")
    set off hand item of {_entity} to a black standing banner
    set off hand item of {_entity} to generateLegendaryLore(off hand item of {_entity}, "Pillage_Captain")
    heal {_entity}
  if {_boss} is "broodmother":
    set helmet of {_entity} to generateLootHelmet()
    set chestplate of {_entity} to generateLootChestplate()
    set leggings of {_entity} to generateLootLeggings()
    set boots of {_entity} to generateLootBoots()
    set off hand item of {_entity} to generateLootShield()
    set held item of {_entity} to generateLootSword()
    set {_entity}'s display name to "&6The Broodmother"
    set movement speed attribute of {_entity} to 0.75 * movement speed attribute of {_entity}
    set attack damage attribute of {_entity} to 1.5 * attack damage attribute of {_entity}
    set maximum health of {_entity} to 250
    set {-evilSkript::%{_entity}%::isBoss} to true
    set {-evilSkript::%{_entity}%::summoner} to true
    set {-evilSkript::%{_entity}%::summoncount} to 10
    set chestplate of {_entity} to generateLegendaryLore(chestplate of {_entity}, "Broodmother")
    set held item of {_entity} to generateLegendaryLore(held item of {_entity}, "Broodmother")
    heal {_entity}
  if {_boss} is "rotwalker":
    set helmet of {_entity} to generateLootHelmet()
    set chestplate of {_entity} to generateLootChestplate()
    set leggings of {_entity} to generateLootLeggings()
    set boots of {_entity} to generateLootBoots()
    set off hand item of {_entity} to generateLootShield()
    set held item of {_entity} to generateLootSword()
    set {_entity}'s display name to "&aRotwalker"
    set movement speed attribute of {_entity} to 0.8 * movement speed attribute of {_entity}
    set attack damage attribute of {_entity} to 2.0 * attack damage attribute of {_entity}
    set maximum health of {_entity} to 150
    set {-evilSkript::%{_entity}%::isBoss} to true
    set {-evilSkript::%{_entity}%::Rotwalker} to true
    set {-evilSkript::%{_entity}%::summoner} to true
    set {-evilSkript::%{_entity}%::summoncount} to 3
    set chestplate of {_entity} to generateLegendaryLore(chestplate of {_entity},"Rotwalker")
    heal {_entity}
  if {_boss} is "void":
    set helmet of {_entity} to generateLootHelmet()
    set chestplate of {_entity} to generateLootChestplate()
    set leggings of {_entity} to generateLootLeggings()
    set boots of {_entity} to generateLootBoots()
    set off hand item of {_entity} to generateLootShield()
    set held item of {_entity} to generateLootSword()
    set {_entity}'s display name to "&9The Void"
    set movement speed attribute of {_entity} to 2.0 * movement speed attribute of {_entity}
    set attack damage attribute of {_entity} to 1.25 * attack damage attribute of {_entity}
    set maximum health of {_entity} to 75
    set {-evilSkript::%{_entity}%::isBoss} to true
    set boots of {_entity} to generateLegendaryLore(boots of {_entity},"Void")
    set held item of {_entity} to generateLegendaryLore(held item of {_entity}, "Void")
    heal {_entity}
  if {_boss} is "headhunter":
    set helmet of {_entity} to generateLootHelmet()
    set chestplate of {_entity} to generateLootChestplate()
    set leggings of {_entity} to generateLootLeggings()
    set boots of {_entity} to generateLootBoots()
    set off hand item of {_entity} to generateLootShield()
    set held item of {_entity} to generateLootSword()
    set {_entity}'s display name to "&8Headhunter"
    set movement speed attribute of {_entity} to 1.2 * movement speed attribute of {_entity}
    set attack damage attribute of {_entity} to 1.25 * attack damage attribute of {_entity}
    set maximum health of {_entity} to 50
    set {-evilSkript::%{_entity}%::isBoss} to true
    set {-evilSkript::%{_entity}%::HeadHunter} to true
    set {-evilSkript::%{_entity}%::summoner} to true
    set {-evilSkript::%{_entity}%::summoncount} to 3
    set held item of {_entity} to generateLootBow()
    set held item of {_entity} to generateLegendaryLore(held item of {_entity}, "Headhunter")
  if {_boss} is "deathgivenlife":
    set helmet of {_entity} to generateLootHelmet()
    set chestplate of {_entity} to generateLootChestplate()
    set leggings of {_entity} to generateLootLeggings()
    set held item of {_entity} to generateLootAxe()
    set off hand item of {_entity} to generateLootBook()
    set {_entity}'s display name to "&0Death Given Life"
    set movement speed attribute of {_entity} to 1.2 * movement speed attribute of {_entity}
    set attack damage attribute of {_entity} to 1.25 * attack damage attribute of {_entity}
    set maximum health of {_entity} to 200
    set {-evilSkript::%{_entity}%::isBoss} to true
    set {-evilSkript::%{_entity}%::deathGivenLife} to true
    set {-evilSkript::%{_entity}%::summoner} to true
    set {-evilSkript::%{_entity}%::summoncount} to 7
    set leggings of {_entity} to generateLootLeggings()
    set leggings of {_entity} to generateLegendaryLore(leggings of {_entity}, "Death Given Life")
    set boots of {_entity} to generateLootBoots()
    set boots item of {_entity} to generateLegendaryLore(boots of {_entity}, "Death Given Life")         
    heal {_entity}
  chance of (2 * {rpgdiff})%:
    set helmet of {_entity} to generateMythicLore(helmet of {_entity})
  chance of (2 * {rpgdiff})%:
    set chestplate of {_entity} to generateMythicLore(chestplate of {_entity})
  chance of (2 * {rpgdiff})%:
    set leggings of {_entity} to generateMythicLore(leggings of {_entity})
  chance of (2 * {rpgdiff})%:
    set boots of {_entity} to generateMythicLore(boots of {_entity})
  chance of (2 * {rpgdiff})%:
    set off hand item of {_entity} to generateMythicLore(off hand item of {_entity})
  chance of (2 * {rpgdiff})%:
    set held item of {_entity} to generateMythicLore(held item of {_entity})	
        
  add uuid of {_entity} to {-evilSkript::bossMobs::*}
  
function makeLunatic(entity:entity):
  set {_entity}'s display name to "&8Lunatic"
  set movement speed attribute of {_entity} to 2 * movement speed attribute of {_entity}
  set maximum health of {_entity} to 5

function isBoss(entity:entity):: boolean:
  if {-evilSkript::%{_entity}%::isBoss} is set:
    return {-evilSkript::%{_entity}%::isBoss}
  return false
    
command /spawnBoss <text> <player>:
  executable by: players
  trigger:
    command executor has permission "rpg.spawn"
    if arg 1 is "DuneRevenant":
      wait 5 seconds
      spawn a husk at location of arg 2:
        makeBoss(the husk, "dune")
    else if arg 1 is "Detonator":
      wait 5 seconds
      spawn a creeper at location of arg 2:
        makeBoss(the creeper, "detonator")
    else if arg 1 is "PillagerCaptain":
      wait 5 seconds
      spawn a evoker at location of arg 2:
        makeBoss(the evoker, "captain")
    else if arg 1 is "Broodmother":
      wait 5 seconds
      spawn a spider at location of arg 2:
        makeBoss(the spider, "broodmother")
    else if arg 1 is "Rotwalker":
      wait 5 seconds
      spawn a zombie at location of arg 2:
        makeBoss(the zombie, "rotwalker")
    else if arg 1 is "Void":
      wait 5 seconds
      spawn an enderman at location of arg 2:
        makeBoss(the enderman, "void")
    else if arg 1 is "Headhunter":
      wait 5 seconds
      spawn a skeleton at location of arg 2:
        makeBoss(the skeleton, "headhunter")
    else if arg 1 is "deathgivenlife":
      wait 5 seconds
      spawn a skeleton at location of arg 2:
        makeBoss(the skeleton, "deathgivenlife")

command /callUpon <text>:
  executable by: players
  trigger:
    hasItems(command executor, getItemCostForSpawn(arg 1, command executor)) is false:
      send "&4You do not have the items to spawn that boss/event!" to player
      stop
    if at least one of:
      arg 1 is "rotwalker"
      arg 1 is "detonator"
      arg 1 is "headhunter"
      arg 1 is "deathgivenlife"
      arg 1 is "broodmother"
      arg 1 is "apocalypse"
      arg 1 is "netherbreach"
    then:
      if time in world "world" is not between 19:00 and 5:00:
        send "&4That Boss/Event cannot be spawned right now!" to player
        stop
    if at least one of:
      arg 1 is "pillagercaptain"
      arg 1 is "bigraid"
    then:
      if time in world "world" is between 19:00 and 5:00:
        send "&4That Boss/Event cannot be spawned right now!" to player
        stop
    loop {evilSkript::bed::*}:
      set {_v} to the vector between player and location of loop-value
      if the length of {_v} is less than 26:
        send "&4You are too close to a player's bed to trigger a boss/event!" to player
        stop
    set {_loc} to location of player
    wait 5 seconds
    if arg 1 is "rotwalker": 
      broadcast "&aA lumbering sickness comes forth..."
      wait 5 seconds  
      spawn a zombie at {_loc}:
        makeBoss(the zombie, "rotwalker")
    else if arg 1 is "deathgivenlife":
      broadcast "&4Magic and Death were always a terrible combo..."
      wait 5 seconds  
      spawn a skeleton at {_loc}:
        makeBoss(the skeleton, "deathgivenlife")      
    else if arg 1 is "detonator": 
      broadcast "&8This is going to be an explosive night..."
      wait 5 seconds  
      spawn a creeper at {_loc}:
        makeBoss(the creeper, "detonator")
    else if arg 1 is "headhunter": 
      broadcast "&8The bones come out to hunt..."
      wait 5 seconds  
      spawn a skeleton at {_loc}:
        makeBoss(the skeleton, "headhunter")
    else if arg 1 is "broodmother": 
      broadcast "&6Don't get swarmed..."
      wait 5 seconds  
      spawn a spider at {_loc}:
        makeBoss(the spider, "broodmother")
    else if arg 1 is "void": 
      broadcast "&9There are some other worldly powers at work here..."
      wait 5 seconds  
      spawn a enderman at {_loc}:
        makeBoss(the enderman, "void")
    else if arg 1 is "pillagercaptain": 
      broadcast "&4There is some evil magic in the air..."
      wait 5 seconds  
      spawn an evoker at {_loc}:
        makeBoss(the evoker, "captain")
    else if arg 1 is "apocalypse": 
      broadcast "&4The Undead Grow Restless..."
      wait 5 seconds  
      set {-apocalypse} to true
    else if arg 1 is "netherbreach": 
      broadcast "&4The monsters of Hell encroach upon the living..."
      wait 5 seconds
      set {-netherbreach} to true
    else if arg 1 is "bigraid": 
      broadcast "&4The raiding drums beat and the horns sing..."
      wait 5 seconds  
      set {-bigraid} to true 
    else:
      send "&4Not a Valid Boss" to player   
    takeItems(command executor, getItemCostForSpawn(arg 1, command executor))

command /ingredientsForSpawn <text>:
  executable by: anyone
  trigger:
    send "%getItemCostForSpawn(arg 1, command executor)% Items Needed for that Boss/Event" to command executor

function getItemCostForSpawn(name: text, player: player):: items:
  if {_name} is "rotwalker":
    return (32 rotten flesh and 16 copper ingot)
  else if {_name} is "detonator":
    return (32 redstone and 4 tnt)
  else if {_name} is "pillagercaptain":
    return (32 lapis lazuli and 4 emerald)
  else if {_name} is "headhunter":
    return (16 bone and 32 arrow)
  else if {_name} is "broodmother":
    return (16 spider eye and 32 string)
  else if {_name} is "void":
    return (8 eye of ender and 16 chorus fruit)
  else if {_name} is "apocalypse":
    set {_item1} to 64 rotten flesh
    set {_item1} to addImbue({_item1}, "Cursed")
    set {_item2} to 32 bone
    set {_item1} to addImbue({_item1}, "Cursed")
    return ({_item1} and {_item2})
  else if {_name} is "netherbreach":
    return (8 blaze rod and 8 magma cream)
  else if {_name} is "bigraid":
    return (64 lapis lazuli and 8 emerald)
    
    

every 10 seconds:

  
  loop all entities:
    {-evilSkript::%loop-entity%::summoner} is true:
      set {-evilSkript::%loop-entity%::summonercount} to {-evilSkript::%loop-entity%::summonercount} + 1
      if {-evilSkript::%loop-entity%::summonercount} is greater than 5:
        set {-evilSkript::%loop-entity%::summonercount} to 5

    if loop-entity is a spider:
      if {-evilSkript::%loop-entity%::isBoss} is true:
        hasEffect(loop-entity, "silenced") is true:
          chance of 30%:
            stop
        loop all players in radius 10 around loop-entity:
          set {_ability} to a random integer between 1 and 3
          if {_ability} is 1:
            createWorldEffect(location of loop-player, "cobweb", 5 seconds, loop-entity-1)
          else if {_ability} is 2:
            createWorldEffect(location of loop-player, "poison_gas", 5 seconds, loop-entity-1) 
          else if {_ability} is 3:
            broadcast "&4A Broodmother takes aim at %loop-player%!"   
            wait 1.5 seconds
            loop entities in radius 3 around loop-player:
              loop-entity-2 is not a spider
              loop-entity-2 is not a cave spider
              applyEffect(loop-entity-2, "venom", 30 seconds, loop-entity-1)
        loop all entities in radius 10 around loop-entity:
          isMonster(loop-entity-2) is false
          chance of 30%:
            applyEffect(loop-entity-2, "cacooned", 5 seconds, loop-entity-1)
            send "&4A Broodmother traps you in a cacoon!" to loop-entity-2

             
    if loop-entity is a zombie:
      if {-evilSkript::%loop-entity%::isButcher} is true:
        hasEffect(loop-entity, "silenced") is true:
          chance of 30%:
            stop
        chance of 30%:
          set {_Block} to 0
          set {_Cone} to 0
          loop 8 times:
            add 1 to {_Block}
            add 2 to {_Cone}
            set {_GetBlock} to block {_Block} blocks infront of loop-entity
            loop all entities in radius {_Cone} around {_GetBlock}:
              loop-entity-2 is not loop-entity-1
              apply slowness 255 to loop-entity-2 for 3 seconds replacing the existing effect				
              apply weakness 2 to loop-entity-2 for 5 seconds replacing the existing effect
              teleport loop-entity-2 to location of the block above the block 2 blocks in front of loop-entity-1
              damage loop-entity-2 by 4
              chance of 50%:
                applyEffect(loop-entity-2, "bleeding", 5 seconds, loop-entity-1)
      if {-evilSkript::%loop-entity%::Rotwalker} is true:
        hasEffect(loop-entity, "silenced") is true:
          chance of 30%:
            stop
        loop all players in radius 20 around loop-entity:
          chance of 30%:
            applyEffect(loop-player, "radiated", 30 seconds, loop-entity-1)
            send "&aYou feel your blood boil!" to loop-player
    if loop-entity is a skeleton:
      {-evilSkript::%loop-entity%::deathGivenLife} is true 
      hasEffect(loop-entity, "silenced") is true:
        chance of 30%:
          stop
      chance of 50%:
        loop all players in radius 20 around loop-entity:
          hasEffect(loop-player, "invisible") is false
          set {_magic} to a random integer between 1 and 2
          if {_magic} is 1:
            broadcast "&4Death Given Life aims a Bone Spear at %loop-player%!"
            wait 1.5 seconds            
            handleMagicDamage(loop-entity-1, loop-player, 15, "physical", true)
          if {_magic} is 2:
            broadcast "&4Death Given Life aims a Bone Cage at %loop-player%!"
            wait 1.5 seconds            
            loop all entities in radius 10 around loop-player:
              isMonster(loop-entity-2) is false
              if loop-entity-2 is not loop-player:
                teleport loop-entity-2 to loop-player
              handleMagicDamage(loop-entity-1, loop-entity-2, 3, "physical", true)
    if loop-entity is an evoker:
      {-evilSkript::%loop-entity%::isBoss} is true
      hasEffect(loop-entity, "silenced") is true:
        chance of 30%:
          stop
      chance of 50%:
        loop all players in radius 20 around loop-entity:
          hasEffect(loop-player, "invisible") is false
          set {_magic} to a random integer between 1 and 5
          if {_magic} is less than 1:
            broadcast "&4A Pillage Captain channels Lightning at %loop-player%!"
            wait 1.5 seconds
            create lightning effect at loop-player
            loop all entities in radius 5 around loop-player:
              loop-entity-2 is not an evoker
              loop-entity-2 is not a ravager
              loop-entity-2 is not a pillager
              loop-entity-2 is not a vindicator
              loop-entity-2 is not a vex
              loop-entity-2 is not a witch
              apply slowness 255 to loop-entity-2 for 3 seconds replacing the existing effect
              handleMagicDamage(loop-entity-1, loop-entity-2, 5, "lightning", true)
          else if {_magic} is less than 2:
            broadcast "&4A Pillage Captain channels Fire at %loop-player%!"
            wait 1.5 seconds
            create a fake explosion at loop-player
            handleMagicDamage(loop-entity-1, loop-player, 3, "fire", true)
            loop all entities in radius 5 around loop-player:
              loop-entity-2 is not an evoker
              loop-entity-2 is not a ravager
              loop-entity-2 is not a pillager
              loop-entity-2 is not a vindicator
              loop-entity-2 is not a vex
              loop-entity-2 is not a witch
              ignite loop-entity-2
              handleMagicDamage(loop-entity-1, loop-entity-2, 1.5, "fire", false)
          else if {_magic} is less than 3:
            broadcast "&4A Pillage Captain channels Earth at %loop-player%!"
            wait 1.5 seconds
            createWorldEffect(location of loop-player, "tremors", 10 seconds, loop-entity-1)
          else if {_magic} is less than 4:
            broadcast "&4A Pillage Captain channels Poison at %loop-player%!"
            wait 1.5 seconds
            createWorldEffect(location of loop-player, "poison_gas", 10 seconds, loop-entity-1)
          else:
            broadcast "&4A Pillage Captain channels Ice at %loop-player%!"
            wait 1.5 seconds
            handleMagicDamage(loop-entity-1, loop-player, 3, "ice", true)
            apply slowness 255 to loop-player for 7.5 seconds replacing the existing effect
            apply weakness 2 to loop-player for 7.5 seconds replacing the existing effect
            applyEffect(loop-player, "vulnerable", 7.5 seconds, loop-entity-1)
  if {-bigraid} is true:
    loop all players:
      loop {evilSkript::bed::*}:
        set {_v} to the vector between location of loop-player and location of loop-value-2
        if the length of {_v} is less than 26: 
          continue
      set {_continue} to true
      set {_x} to a random number between -50 and 50
      set {_x} to the x coordinate of loop-player + {_x}
      set {_z} to a random number between -50 and 50
      set {_z} to the z coordinate of loop-player + {_z}
      set {_y} to a random number between -5 and 5
      set {_y} to the y coordinate of loop-player + {_y}
      set {_loc} to the location at {_x}, {_y}, {_z} of world "world"
      block at {_loc} is not air
      block at {_loc} is not water
      loop blocks in radius 2.99 around {_loc}:
        loop-block is not air:
          set {_continue} to false
      if {_continue} is true:
        set {_chance} to a random number between 1 and 100
        if {_chance} is greater than 90:
          spawn 1 ravager at {_loc}
        else if {_chance} is greater than 75:
          spawn 1 vindicator at {_loc}
        else if {_chance} is greater than 50:
          spawn 1 evoker at {_loc}
        else if {_chance} is greater than 25:
          spawn 1 witch at {_loc}
        else:
          spawn 3 vex at {_loc}
        spawn 3 pillagers at {_loc}

every 3 seconds:
  loop all entities:
    if loop-entity is a husk:
      if {-evilSkript::%loop-entity%::isBoss} is true:
        loop all players in radius 15 around loop-entity-1:
          chance of 50%:
            set block 5 blocks above loop-player to sand
          if block below loop-player is sand:
            chance of 50%:
              set block below loop-player to air
      
    

command /rpgdifficulty <number>:
  trigger:
    if arg 1 is less than 0.01:
      set {rpgdiff} to 0.01
    else:
      set {rpgdiff} to arg 1	
    broadcast "&cSet Difficulty Modifier to %{rpgdiff}%"

command /getrpgdifficulty:
  trigger:
    broadcast "Difficulty is: %{rpgdiff}%"

command /spawnSpecial <text> <number>:
  executable by: players
  trigger:
    if arg 1 is "Disease Creeper":
      loop arg 2 times:
        spawn a creeper at player:
          makeSpecial(the creeper)
    if arg 1 is "Dragon Disciple":
      loop arg 2 times:
        spawn an enderman at player:
          makeSpecial(the enderman)
    if arg 1 is "Zombie Warrior":
      loop arg 2 times:
        spawn a zombie at player:
          makeSpecial(the zombie)
    if arg 1 is "Skeleton Warrior":
      loop arg 2 times:
        spawn a skeleton at player:
          makeSpecial(the skeleton)
  
     
