on script unload:
  loop {-evilSkript::bossMobs::*}:
    killBoss(loop-index)
  delete {-evilSkript::bossMobs::*}

function killBoss(uuid: text):
	kill getByUUID({_uuid})
  
on spawn:
  spawn reason is natural
  entity is a monster
  set {_chance} to log({rpgdiff}) * 12.5
  {_chance} <= 0:
    stop
  if entity is a zombie:
    if {-netherbreach} is true:
      spawn 1 zombified piglin at entity
      spawn 1 piglin at entity
      chance of 10%:
        spawn 1 piglin brute at entity
    if entity is not a baby zombie:
      chance of ({_chance}/5)%:
        makeSpecial(entity)
      chance of ({_chance}/5)%:
        makeSummoner(entity)
    else:
      chance of ({_chance}/5)%:
        makeSpecial(entity)     
    
  else if entity is a skeleton:
    if {-netherbreach} is true:
      spawn 1 wither skeleton at entity
    chance of ({_chance}/5)%:
      makeSpecial(entity)
    chance of ({_chance}/5)%:
      makeSummoner(entity)
  else if entity is a spider:
    if {-netherbreach} is true:
      spawn 1 hoglin at the entity
    chance of ({_chance}/5)%:
      makeSpecial(entity)
  else if entity is a enderman:
    chance of ({_chance}/5)%:
      makeSpecial(entity)
  else if entity is a creeper:
    if {-netherbreach} is true:
      spawn 1 blaze at entity
    chance of ({_chance}/5)%:
      makeSpecial(entity)
  else if entity is a slime:
    if {-netherbreach} is true:
      spawn 1 magma cube at entity
  else if entity is a phantom:
    if {-netherbreach} is true:
      spawn 1 ghast at entity
  scriptDebugBroadcastType("difficulty", "Attempting to spawn a boss at %{_chance}% chance with %{rpgdiff}% difficulty")
  chance of ({_chance} / 50)%:
    makeBoss(entity)

  if {-apocalypse} is true:
    isMonster(entity) is true:
      set {_n} to a random number between 1 and 10
      loop {_n} times:
        spawn 1 zombie at entity:
          chance of ({_chance} / 5)%:
            makeSpecial(entity)


  

on spawn:
  isMinion(entity) is false
  if at least one of:
    entity is a monster
    entity is an iron golem
    entity is a wolf
    entity is a polar bear
  then:
    if {rpgdiff} is not set:
      set {rpgdiff} to 1
    set attack damage attribute of entity to (1.1^({rpgdiff} - 1)) * attack damage attribute of entity
    set maximum health of entity to (1.1^({rpgdiff} - 1)) * maximum health of entity
    heal entity
  isMonster(entity) is true:
    set {_itemchance} to 2.5
    if at least one of:
      {-netherbreach} is true
      {-apocalypse} is true
    then:
      set {_itemchance} to 5
    chance of {_itemchance}%:
      set helmet of entity to generateLootHelmet()
    chance of {_itemchance}%:
      set chestplate of entity to generateLootChestplate()
    chance of {_itemchance}%:
      set leggings of entity to generateLootLeggings()
    chance of {_itemchance}%:
      set boots of entity to generateLootBoots()
    chance of {_itemchance}%:
      set held item of entity to generateLootSword()
    chance of {_itemchance}%:
      set off hand item of entity to generateLootShield() 

on death:
  victim is a monster:
    set {rpgdiff} to {rpgdiff} + 0.0025
    if mod({rpgdiff}, 0.2) is 0:
      broadcast "Difficulty is now: %{rpgdiff}%"	

  victim is a player:
    set {rpgdiff} to {rpgdiff} - 0.3
    broadcast "Difficulty is now: %{rpgdiff}%"

every 5 seconds:
  if {rpgdiff} is less than 0.05:
    set {rpgdiff} to 0.05
  if time in world "world" is between 19:00 and 5:00:
    if:
      {-netherbreach} is not true
      {-apocalypse} is not true
    then:
      if {lastInvasion} is not set:
        set {lastInvasion} to 0.5 hours ago
      difference between {lastInvision} and now is more than 1 hour:
        set {_chance} to log({rpgdiff}) * 12.5 / 100
        if {_chance} > 0:
          chance of {_chance}%:
            set {lastInvasion} to now
            set {_odds} to random number between 1 and 100
            if {_odds} is less than 60:
              set {-netherbreach} to true
              broadcast "&4A Nether Breach Opens..."
            else if {_odds} is less than 100:
              set {-apocalypse} to true
              broadcast "&4The Undead Grow Restless..."
              
  else:
    if {-netherbreach} is true:
      set {-netherbreach} to false
      broadcast "&4A Nether Breach Closes..."
    if {-apocalypse} is true:
      set {-apocalypse} to false
      broadcast "&4The Undead are put to rest..."

  
on weather change to rain:
  chance of 15%:
    set {-severestorms} to true
    loop all players:
      if at least one of:
        biome of loop-player is desert
        biome of loop-player is badlands
      then:
        send "&6A severe sandstorm picks up!" to loop-player
      else:
        send "&4An Acid Rain Pours!" to loop-player

on weather change:
  weather is not rain:
    if {-severestorms} is not false:
      {-severestorms} is true:
        broadcast "&cSevere Storms End..."
      set {-severestorms} to false

command /worldevents <text> <boolean>:
  trigger:
    if command executor does not have permission "rpg.spawn":
      send "&cYou do not have access to that command." to command executor
      stop
    if arg 1 is "severe storms":
      set {-severestorms} to arg 2 
      if arg 2 is true:
        set weather in "world" to rain
      scriptDebugBroadcastType("worldevents", "Setting {-severestorms} to %arg 2%")
      broadcast "&c{-severestorms} set to %arg 2%"
    else if arg 1 is "nether breach":
      set {-netherbreach} to arg 2
      if arg 2 is true:
        set time in "world" to 20:00
      scriptDebugBroadcastType("worldevents", "Setting {-neatherbreach} to %arg 2%")
      broadcast "&c{-netherbreach} set to %arg 2%"
    else if arg 1 is "apocalypse":
      set {-apocalypse} to arg 2
      if arg 2 is true:
        set time in "world" to 20:00
      scriptDebugBroadcastType("worldevents", "Setting {-neatherbreach} to %arg 2%")
      broadcast "&c{-apocalypse} set to %arg 2%"
          
    else:
      send "&cInvalid World Event." to command executor 

command /displayevents:
  trigger:
    broadcast "&cBroadcasting Events"
    broadcast "&6Severe Storms is %{-severestorms}%"
    broadcast "&6Nether Breach is %{-netherbreach}%"
    broadcast "&6Apocalypse is %{-Apocalypse}%"
    
      
function makeSpecial(entity: entity):
  {_entity} is a zombie:
    if {_entity} is not a baby zombie:
      set attack damage attribute of {_entity} to 1.8 * attack damage attribute of {_entity}
      set movement speed attribute of {_entity} to 1.2 * movement speed attribute of {_entity}
      set maximum health of {_entity} to 2.2 * maximum health of {_entity}
      heal {_entity}
      equip {_entity} with iron helmet
      equip {_entity} with iron chestplate
      equip {_entity} with iron leggings
      equip {_entity} with iron boots
      set {_entity}'s held item to iron sword
      loop 2 times:
        spawn a skeleton at {_entity}
    else:
      set attack damage attribute of {_entity} to 2.0 * attack damage attribute of {_entity}
      set movement speed attribute of {_entity} to 1.5 * movement speed attribute of {_entity}
      set maximum health of {_entity} to 2.0 * maximum health of {_entity}
      set size of {_entity} to 1.25 * size of {_entity}
      heal {_entity}
      equip {_entity} with leather helmet
      equip {_entity} with leather chestplate
      equip {_entity} with leather leggings
      equip {_entity} with leather boots
      set {_entity}'s held item to gold sword
      loop 2 times:
        spawn a skeleton at {_entity}
  else if {_entity} is a skeleton:
    set attack damage attribute of {_entity} to 2.0 * attack damage attribute of {_entity}
    set movement speed attribute of {_entity} to 1.3 * movement speed attribute of {_entity}
    set maximum health of {_entity} to 1.7 * maximum health of {_entity}
    equip {_entity} with chain helmet
    equip {_entity} with chain chestplate
    equip {_entity} with chain leggings
    equip {_entity} with chain boots
    set {_entity}'s held item to iron sword
    loop 2 times:
      spawn a zombie at {_entity}
  else if {_entity} is a spider:
    loop 3 times:
      spawn a cave spider at {_entity}
  else if {_entity} is an enderman:
    set attack damage attribute of {_entity} to 1.5 * attack damage attribute of {_entity}
    set movement speed attribute of {_entity} to 2.0 * movement speed attribute of {_entity}
    set maximum health of {_entity} to 1.5 * maximum health of {_entity}
    heal {_entity}
    loop 3 times:
      spawn a shulker at {_entity}
  else if {_entity} is a creeper:
    set movement speed attribute of {_entity} to 2 * movement speed attribute of {_entity}
    set maximum health of {_entity} to 5.0 * maximum health of {_entity}
    set {-evilSkript::%{_entity}%::disease} to true
    heal {_entity}
    loop 3 times:
      spawn a creeper at {_entity}

function summonButcher(player:player, chance:number):
  scriptDebugBroadcastType("difficulty", "Attempting to spawn a Butcher at %{_player}%") 
  set {_loc} to location of {_player}
  chance of {_chance}%:
    broadcast "A presence of evil surrounds %{_player}%!" 
    wait 15 seconds
    spawn 1 zombie at the location above {_loc}:
      set the zombie's display name to "&4The Butcher"
      set attack damage attribute of the zombie to 2.5 * attack damage attribute of the zombie
      set movement speed attribute of the zombie to 2.0 * movement speed attribute of the zombie
      set maximum health of the zombie to 200
      heal the zombie
      set {_temp} to the zombie
      set {-evilSkript::%{_temp}%::isBoss} to true
      set {-evilSkript::%{_temp}%::isButcher} to true
      set helmet of the zombie to generateLootHelmet()
      set chestplate of the zombie to generateLootChestplate()
      set leggings of the zombie to generateLootLeggings()
      set boots of the zombie to generateLootBoots()
      set held item of the zombie to generateLootSword()
      set off hand item of the zombie to generateLootShield() 
      scriptDebugBroadcastType("difficulty", "Spawning a Butcher at %{_player}%")  
      add uuid of the zombie to {-evilSkript::bossMobs::*}

command /spawnButcher <player> <number>:
  executable by: anyone
  trigger:
    if command executor is a player:
      if command executor does not have permission "rpg.spawn":
        send "&4You do not have access to that command." to command executor
    scriptDebugBroadcastType("difficulty", "%command executor% spawns a Butcher at %arg 1%") 
    summonButcher(arg 1, arg 2)

command /spawnrates:
  executable by: anyone
  trigger:
    broadcast "Special Chance: log(%{rpgdiff}%) * 12.5 / 5 = %log({rpgdiff}) * 12.5 / 5% PERCENT"
    broadcast "Boss Chance: log(%{rpgdiff}%) * 12.5 / 50 = %log({rpgdiff}) * 12.5 / 50% PERCENT"
    broadcast "Butcher Chance: log(%{rpgdiff}%) * 12.5 / 100 = %log({rpgdiff}) * 12.5 / 100% PERCENT"
    broadcast "Netherbreach/Apocalypse Chance: log(%{rpgdiff}%) * 12.5 / 100 = %log({rpgdiff}) * 12.5 / 100% PERCENT"
    broadcast "Mobs Attack Damage Bonus: %(1.1^({rpgdiff} - 1))%x"
    broadcast "Mobs Health Bonus: %(1.1^({rpgdiff} - 1))%x"
        
on explosion:
  if event-entity is a creeper:
    creeperDetonate(event-entity)


on death:
  creeperDetonate(victim)

function creeperDetonate(entity:entity):
  if {-evilSkript::%{_entity}%::disease} is true:
    createWorldEffect(location of {_entity}, "disease", 20 seconds, {_entity})
  if {-evilSkript::%{_entity}%::detonator} is true:
    create an explosion with force 3 at {_entity}
    loop blocks in radius 5.99 around {_entity}:
      loop-block is not air
      loop-block is not bedrock
      break loop-block naturally
    if {-evilSkript::%{_entity}%::crassus} is true:
      loop blocks in radius 7.99 around {_entity}:
        loop-block is not air
        if at least one of:
          loop-block is stone
          loop-block is deepslate
          loop-block is grass block
          loop-block is dirt
          loop-block is sand
          loop-block is red sand
        then:
          loop blocks in radius 1 around loop-block:
            loop-block-2 is not air
            loop-block-2 is not any ore
            loop-block-1 is not bedrock
            chance of 30%:
              set {_odds} to rollDice(1,100)
              if {_odds} is less than 10:
                set loop-block-1 to coal ore
              else if {_odds} is less than 20:
                set loop-block-1 to copper ore
              else if {_odds} is less than 50:
                set loop-block-1 to iron ore
              else if {_odds} is less than 80:
                set loop-block-1 to gold ore
              else if {_odds} is less than 85:
                if {-netherbreach} is true:
                  set loop-block-1 to glowstone block
                  exit 1 loop
                set loop-block-1 to redstone ore
              else if {_odds} is less than 95:
                set loop-block-1 to lapis lazuli ore
                if {-netherbreach} is true:
                  set loop-block-1 to quartz ore
                  exit 1 loop
              else if {_odds} is less than 98:
                set loop-block-1 to diamond ore
              else:
                if {-netherbreach} is true:
                  chance of 30%:
                    set loop-block-1 to ancient debris
                    exit 1 loop
                set loop-block-1 to emerald ore
                
    loop all entities in radius 10 around {_entity}:
      loop-entity is not a dropped item
      loop-entity is alive
      damage loop-entity by 500
    broadcast "&eDetonator Explosion!"
    
function makeSummoner(entity:entity):
  if at least one of:
    {_entity} is a skeleton
    {_entity} is a zombie
  then:
    set {_entity}'s held item to a stick
    set {-evilSkript::%{_entity}%::summoner} to true
    set {-evilSkript::%{_entity}%::summoncount} to 3

function makeBoss(entity:entity):
  {_entity} is a husk:
    set {_entity}'s display name to "&6Dune Revenant"
    set attack damage attribute of {_entity} to 2 * attack damage attribute of {_entity}
    set movement speed attribute of {_entity} to 2.0 * movement speed attribute of {_entity}
    set maximum health of {_entity} to 100
    heal {_entity}
    set {-evilSkript::%{_entity}%::dunerev} to true
    set {-evilSkript::%{_entity}%::isBoss} to true
    set helmet of {_entity} to generateLootHelmet()
    set chestplate of {_entity} to generateLootChestplate()
    set leggings of {_entity} to generateLootLeggings()
    set boots of {_entity} to generateLootBoots()
    set held item of {_entity} to generateLootSword()
    set off hand item of {_entity} to generateLootShield()
  {_entity} is a creeper:
    set {_entity}'s display name to "&8Detonator"
    set movement speed attribute of {_entity} to 0.5 * movement speed attribute of {_entity}
    set maximum health of {_entity} to 200
    set {-evilSkript::%{_entity}%::detonator} to true
    set {-evilSkript::%{_entity}%::summoner} to true
    set {-evilSkript::%{_entity}%::summoncount} to 4
    chance of 30%:
      set {-evilSkript::%{_entity}%::crassus} to true 
      set {_entity}'s display name to "&eCrassus Detonator"  
    set {-evilSkript::%{_entity}%::isBoss} to true
    heal {_entity}
  {_entity} is an evoker:
    set {_entity}'s display name to "&4Pillage Captain"
    set movement speed attribute of {_entity} to 1.25 * movement speed attribute of {_entity}
    set attack damage attribute of {_entity} to 1.5 * attack damage attribute of {_entity}
    set maximum health of {_entity} to 100
    set {-evilSkript::%{_entity}%::isBoss} to true
    set {-evilSkript::%{_entity}%::summoner} to true
    set {-evilSkript::%{_entity}%::summoncount} to 3
    set helmet of {_entity} to generateLootHelmet()
    set chestplate of {_entity} to generateLootChestplate()
    set leggings of {_entity} to generateLootLeggings()
    set boots of {_entity} to generateLootBoots()
    set held item of {_entity} to generateLootSword()
    set off hand item of {_entity} to generateLootShield()
    heal {_entity}
  {_entity} is a spider:
    set {_entity}'s display name to "&6The Broodmother"
    set movement speed attribute of {_entity} to 0.5 * movement speed attribute of {_entity}
    set attack damage attribute of {_entity} to 1.5 * attack damage attribute of {_entity}
    set maximum health of {_entity} to 250
    set {-evilSkript::%{_entity}%::isBoss} to true
    set {-evilSkript::%{_entity}%::summoner} to true
    set {-evilSkript::%{_entity}%::summoncount} to 7
    set helmet of {_entity} to generateLootHelmet()
    set chestplate of {_entity} to generateLootChestplate()
    set leggings of {_entity} to generateLootLeggings()
    set boots of {_entity} to generateLootBoots()
    set held item of {_entity} to generateLootSword()
    set off hand item of {_entity} to generateLootShield()
    heal {_entity}
  {_entity} is a zombie:
    set {_entity}'s display name to "&aRotwalker"
    set movement speed attribute of {_entity} to 0.8 * movement speed attribute of {_entity}
    set attack damage attribute of {_entity} to 2.0 * attack damage attribute of {_entity}
    set maximum health of {_entity} to 150
    set {-evilSkript::%{_entity}%::isBoss} to true
    set {-evilSkript::%{_entity}%::Rotwalker} to true
    set {-evilSkript::%{_entity}%::summoner} to true
    set {-evilSkript::%{_entity}%::summoncount} to 3
    set helmet of {_entity} to generateLootHelmet()
    set chestplate of {_entity} to generateLootChestplate()
    set leggings of {_entity} to generateLootLeggings()
    set boots of {_entity} to generateLootBoots()
    set held item of {_entity} to generateLootSword()
    set off hand item of {_entity} to generateLootShield()
    heal {_entity}
    
  add uuid of {_entity} to {-evilSkript::bossMobs::*}
  
function makeLunatic(entity:entity):
  set {_entity}'s display name to "&8Lunatic"
  set movement speed attribute of {_entity} to 2 * movement speed attribute of {_entity}
  set maximum health of {_entity} to 5
    
command /spawnBoss <text>:
  executable by: players
  trigger:
    command executor has permission "rpg.spawn"
    if arg 1 is "DuneRevenant":
      spawn a husk at the player:
        makeBoss(the husk)
    else if arg 1 is "Detonator":
      spawn a creeper at the player:
        makeBoss(the creeper)
    else if arg 1 is "PillagerCaptain":
      spawn a evoker at the player:
        makeBoss(the evoker)
    else if arg 1 is "Broodmother":
      spawn a spider at the player:
        makeBoss(the spider)
    else if arg 1 is "Rotwalker":
      spawn a zombie at the player:
        makeBoss(the zombie)
    
    

every 10 seconds:
  loop all entities:
    {-evilSkript::%loop-entity%::summoner} is true:
      set {-evilSkript::%loop-entity%::summonercount} to {-evilSkript::%loop-entity%::summonercount} + 1
      if {-evilSkript::%loop-entity%::summonercount} is greater than 5:
        set {-evilSkript::%loop-entity%::summonercount} to 5

    if loop-entity is a spider:
      if {-evilSkript::%loop-entity%::isBoss} is true:
        loop all entities in radius 10 around loop-entity:
          loop-entity-2 is not loop-entity-1
          loop-entity-2 is not a spider
          if chance of 30%:
            createWorldEffect(block at location of loop-entity-2, "cobweb", 5 seconds, loop-entity-1)
            exit 1 loop
          if chance of 30%:
            createWorldEffect(block at location of loop-entity-2, "poison_gas", 5 seconds, loop-entity-1)    
    if loop-entity is a zombie:
      if {-evilSkript::%loop-entity%::isButcher} is true:
        loop all entities in radius 15 around loop-entity-1:
          loop-entity-2 is not a monster
          loop-entity-2 is not a dropped item
          loop-entity-2 is alive
          chance of 30%:
            set {_vec} to vector between loop-entity-2 and loop-entity-1
            set y component of {_vec} to 0
            set {_vec} to normalized {_vec}
            push loop-entity-2 {_vec} with force 1.2
            push loop-entity-2 upwards with force 0.3
            exit loop
      if {-evilSkript::%loop-entity%::Rotwalker} is true:
        applyEffect(loop-entity, "disease", 10 seconds)
        createWorldEffect(block at location of loop-entity, "disease", 5 seconds, loop-entity)

every 3 seconds:
  loop all entities:
    if loop-entity is a husk:
      if {-evilSkript::%loop-entity%::isBoss} is true:
        loop all players in radius 15 around loop-entity-1:
          chance of 50%:
            set block 5 blocks above loop-player to sand
          if block below loop-player is sand:
            chance of 50%:
              set block below loop-player to air
      
    

command /rpgdifficulty <number>:
  trigger:
    if arg 1 is less than 0.01:
      set {rpgdiff} to 0.01
    else:
      set {rpgdiff} to arg 1	
    broadcast "&cSet Difficulty Modifier to %{rpgdiff}%"

command /getrpgdifficulty:
  trigger:
    broadcast "Difficulty is: %{rpgdiff}%"

command /spawnSpecial <text> <number>:
  executable by: players
  trigger:
    if arg 1 is "Disease Creeper":
      loop arg 2 times:
        spawn a creeper at player:
          makeSpecial(the creeper)
    if arg 1 is "Dragon Disciple":
      loop arg 2 times:
        spawn an enderman at player:
          makeSpecial(the enderman)
    if arg 1 is "Zombie Warrior":
      loop arg 2 times:
        spawn a zombie at player:
          makeSpecial(the zombie)
    if arg 1 is "Skeleton Warrior":
      loop arg 2 times:
        spawn a skeleton at player:
          makeSpecial(the skeleton)
  
     
